/* ui_frontend.c generated by valac 0.56.19, the Vala compiler
 * generated from ui_frontend.vala, do not modify */

/* ui_frontend.vala*/

#include <glib.h>
#include "vala_exports.h"
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>

#if !defined(VALA_STRICT_C)
#if !defined(__clang__) && defined(__GNUC__) && (__GNUC__ >= 14)
#pragma GCC diagnostic warning "-Wincompatible-pointer-types"
#elif defined(__clang__) && (__clang_major__ >= 16)
#pragma clang diagnostic ignored "-Wincompatible-function-pointer-types"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#endif
#endif

enum  {
	CONTROLLER_0_PROPERTY,
	CONTROLLER_NUM_PROPERTIES
};
static GParamSpec* controller_properties[CONTROLLER_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

static gpointer controller_parent_class = NULL;

void run_objective_cxx_pipeline (void);
void* engine_create (void);
guint32 engine_get_checksum (void* handle);
void engine_destroy (void* handle);
static GType controller_get_type_once (void);
static gint _vala_main (gchar** args,
                 gint args_length1);

void
controller_execute (Controller* self)
{
	void* engine = NULL;
	void* _tmp0_;
	guint32 initial_sum = 0U;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	g_return_if_fail (self != NULL);
	g_print ("[Vala] Starting multi-language pipeline...\n");
	g_print ("[Vala] Invoking Objective-C++ layer...\n");
	run_objective_cxx_pipeline ();
	g_print ("[Vala] Allocating raw C++ engine directly...\n");
	_tmp0_ = engine_create ();
	engine = _tmp0_;
	initial_sum = engine_get_checksum (engine);
	_tmp1_ = g_strdup_printf ("%u", initial_sum);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat ("[Vala] Initial core checksum: 0x", _tmp2_, "\n", NULL);
	_tmp4_ = _tmp3_;
	g_print ("%s", _tmp4_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	engine_destroy (engine);
	g_print ("[Vala] Teardown complete.\n");
}

Controller*
controller_construct (GType object_type)
{
	Controller * self = NULL;
	self = (Controller*) g_object_new (object_type, NULL);
	return self;
}

Controller*
controller_new (void)
{
	return controller_construct (TYPE_CONTROLLER);
}

static void
controller_class_init (ControllerClass * klass,
                       gpointer klass_data)
{
	controller_parent_class = g_type_class_peek_parent (klass);
}

static void
controller_instance_init (Controller * self,
                          gpointer klass)
{
}

static GType
controller_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ControllerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) controller_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Controller), 0, (GInstanceInitFunc) controller_instance_init, NULL };
	GType controller_type_id;
	controller_type_id = g_type_register_static (G_TYPE_OBJECT, "Controller", &g_define_type_info, 0);
	return controller_type_id;
}

GType
controller_get_type (void)
{
	static volatile gsize controller_type_id__once = 0;
	if (g_once_init_enter (&controller_type_id__once)) {
		GType controller_type_id;
		controller_type_id = controller_get_type_once ();
		g_once_init_leave (&controller_type_id__once, controller_type_id);
	}
	return controller_type_id__once;
}

static gint
_vala_main (gchar** args,
            gint args_length1)
{
	Controller* app = NULL;
	Controller* _tmp0_;
	gint result;
	_tmp0_ = controller_new ();
	app = _tmp0_;
	controller_execute (app);
	result = 0;
	_g_object_unref0 (app);
	return result;
}

int
main (int argc,
      char ** argv)
{
	return _vala_main (argv, argc);
}

