/* vala_exports.h generated by valac 0.56.19, the Vala compiler, do not modify */

#ifndef __SRC_VALA_EXPORTS_H__
#define __SRC_VALA_EXPORTS_H__

#include <glib-object.h>
#include <glib.h>

G_BEGIN_DECLS

#if !defined(VALA_EXTERN)
#if defined(_MSC_VER)
#define VALA_EXTERN __declspec(dllexport) extern
#elif __GNUC__ >= 4
#define VALA_EXTERN __attribute__((visibility("default"))) extern
#else
#define VALA_EXTERN extern
#endif
#endif

#define TYPE_CONTROLLER (controller_get_type ())
#define CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONTROLLER, Controller))
#define CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONTROLLER, ControllerClass))
#define IS_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONTROLLER))
#define IS_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONTROLLER))
#define CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONTROLLER, ControllerClass))

typedef struct _Controller Controller;
typedef struct _ControllerClass ControllerClass;
typedef struct _ControllerPrivate ControllerPrivate;

struct _Controller {
	GObject parent_instance;
	ControllerPrivate * priv;
};

struct _ControllerClass {
	GObjectClass parent_class;
};

VALA_EXTERN GType controller_get_type (void) G_GNUC_CONST ;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Controller, g_object_unref)
VALA_EXTERN void controller_execute (Controller* self);
VALA_EXTERN Controller* controller_new (void);
VALA_EXTERN Controller* controller_construct (GType object_type);

G_END_DECLS

#endif
